name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=true docker build . --file Dockerfile --tag dancer-build:$(date +%s) --output out
