name: Windows build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt --prefer-binary

    - name: Build executeable
      run: pyinstaller kinter.spec

    - name: Download FFMpeg
      run: certutil.exe -urlcache -f https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z ffmpeg.7z

    - name: Unpack FFMpeg
      run: tar -C ./dist -xvf ffmpeg.7z --strip-components=2 "ffmpeg*/bin/ffmpeg.exe"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          dist
          !dist/**/*.md